# Netlify configuration file
#
# This file contains the configuration for deploying the website on Netlify.
# For more information, see https://docs.netlify.com/configure-builds/file-based-configuration/

# Build settings
[build]
  # The command to build the site. This command is defined in your package.json.
  command = "npm run build"
  # The directory to publish, which contains the built site.
  # It's a best practice to use a dedicated directory like "dist" or "public".
  publish = "dist"

# Build environment settings
[build.environment]
  # Specify the Node.js version to use for the build.
  NODE_VERSION = "16"
  # Additional flags for the npm command.
  NPM_FLAGS = "--legacy-peer-deps"

# Redirects and rewrites
# This rule is for Single Page Applications (SPAs) to ensure all routes are handled by index.html.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and caching headers
# These headers enhance security and improve performance.

[[headers]]
  for = "/*"
  [headers.values]
    # Prevents the site from being rendered in an iframe.
    X-Frame-Options = "DENY"
    # Prevents browsers from MIME-sniffing the content type.
    X-Content-Type-Options = "nosniff"
    # Enables the XSS filter in browsers.
    X-XSS-Protection = "1; mode=block"
    # Controls how much referrer information is sent.
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy (CSP) to prevent a wide range of attacks.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.youtube.com https://s.ytimg.com https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://i.ytimg.com https://img.youtube.com https://www.google-analytics.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.googleapis.com https://firestore.googleapis.com https://*.firebaseio.com; frame-src 'self' https://www.youtube.com https://www.google.com;"

# Caching policy for static assets
# Cache assets for a long time to improve performance for returning visitors.
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
