[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirige toutes les routes vers index.html (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
